### PR TITLE
Add php-xml

### PR DESCRIPTION
**Pull request by farooqkz**
I want it for running a PHP forum software.

### CODE REVIEW

**Comment by farooqkz** [comment]
Please don't merge it I've written the wrong package...

**Comment by daurnimator** [comment]
Please squash away your first commit.

**Comment by farooqkz** [comment]
You mean I should combine these two commits?
Probably a noob question because I don't know much about git.

**Comment by farooqkz** [comment]
Finally I did the signed commit. Thank you reynir :)

**Comment by farooqkz** [comment]
It is merge-able now.

**Pull request merged**
