### PR TITLE
Ansible: Use systematically the systemd module

### PR DESCRIPTION
**Pull request by KellerFuchs**
Just skip the task when running in Docker (since it's pointless to try and enable services there, as systemd won't run)

### CODE REVIEW

**Comment by RyanSquared** [comment]
See #73. This works for Docker but not for things like lxc, which we should also support.

cc @benharri as I believe they have experience working shell-server with lxc

**Comment by benharri** [comment]
I've tried taking a stab at creating and lxd image. neither lxd nor lxc have been working. for lxd auditd fails to install and kills the playbook.

**Comment by KellerFuchs** [comment]
@benharri Is there a reasonablish way to make the shell-server image have a woking systemd under lxc/lxd?

@RyanSquared If shell-server already doesn't work under lxc/lxd, I don't think we should make that a blocker.

**Comment by benharri** [comment]
as far as I can tell systemd was working fine under lxd. I still wasn't sure why the auditd install failed.

**Comment by KellerFuchs** [comment]
@benharri OK, then let's get this reviewed/merged, and I can look at fixing the auditd stuff in #74.

**Pull request merged**
