### PR TITLE
Add emacs25-nox package

### PR DESCRIPTION
**Pull request by darkfeline**

### CODE REVIEW

**Comment by darkfeline** [comment]
Looks like nodejs-dev is broken?

```
The following packages have unmet dependencies:\n nodejs-dev : Depends: libssl1.0-dev (>= 1.0.2) but it is not going to be installed
```

**Comment by RyanSquared** [comment]
Shocker, it's been broken many times. I've noticed that there's an `emacs25` already installed but I'm not sure what that's about.

**Comment by RyanSquared** [comment]
Actually, `emacs25-nox` is installed on our boxes (even if not represented in package list) as well. I'm not sure why it's not showing up. Would require manual testing.

**Comment by RyanSquared** [comment]
This already seems to be implemented in master.

**Pull request closed without merging**
